# server configuration
#"%dev":
#  quarkus:
#    http:
#      port: 8181
quarkus:

  http:
    cors: true
    ssl:
      certificate:
        key-store-file: siri-xlite.jks
        key-store-password: siri-xlite
    http2: false

  datasource:
    db-kind: postgresql
    username: siri-xlite
    password: siri-xlite
    #    jdbc:
    #      url: jdbc:postgresql://postgres/siri-xlite
    reactive:
      url: vertx-reactive:postgresql://postgres/siri-xlite

  hibernate-orm:
    jdbc:
      timezone: "Europe/Paris"
    second-level-caching-enabled: false
    database:
      charset: UTF-8
      generation: create
    log:
      sql: false

  infinispan-embedded:
    xml-config: infinispan.xml

#  flyway:
#    migrate-at-start: false
#    schemas: public

# application configuration
siri-xlite:
  lines-discovery:
    max-age: 30
    s-maxage: 3600
  stoppoints-discovery:
    max-age: 30
    s-maxage: 3600
  stop-monitoring:
    max-age: 30
    s-maxage: 600
  estimated-timetable:
    max-age: 30
    s-maxage: 600
  estimated-vehicle-journey:
    max-age: 30
    s-maxage: 60

  log:
    category: