

# server configuration
quarkus:

  datasource:
    db-kind: postgresql
    username: siri-xlite
    password: siri-xlite
#    jdbc:
#      url: jdbc:postgresql://postgres/siri-xlite
    reactive:
      url: vertx-reactive:postgresql://postgres/siri-xlite

  hibernate-orm:
    second-level-caching-enabled: false
    statement-batch-size: 1000
    database:
      generation: none
    log:
      sql: true

  infinispan-embedded:
    xml-config: infinispan.xml

#  flyway:
#    migrate-at-start: false
#    schemas: public

# application configuration
siri-xlite:
  port: 8443
  lines-discovery:
    max-age: 30
    s-maxage: 3600
  stoppoints-discovery:
    max-age: 30
    s-maxage: 3600
  stop-monitoring:
    max-age: 30
    s-maxage: 600
  estimated-timetable:
    max-age: 30
    s-maxage: 600
  estimated-vehicle-journey:
    max-age: 30
    s-maxage: 60

  log:
    category: