version: "3.3"
services:

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: siri-xlite
      POSTGRES_PASSWORD: siri-xlite
      POSTGRES_DB: siri-xlite
      TZ: Europe/Paris
      PGTZ: Europe/Paris
    volumes:
       - /tmp/siri:/tmp/siri:z

  siri-xlite:
    build:
      context: "../../../"
      dockerfile: "src/main/docker/siri-xlite/Dockerfile"
    depends_on:
      - "postgres"
    ports:
      - "8080:8080"
      - "8443:8443"
    user: "1001:1001"
    volumes:
      - /tmp/siri:/tmp/siri:z

  varnish:
    build:
      context: "../../../"
      dockerfile: "src/main/docker/varnish/Dockerfile"
    depends_on:
      - "siri-xlite"
    tmpfs: /var/lib/varnish:exec

  haproxy:
    build:
      context: "../../../"
      dockerfile: "src/main/docker/haproxy/Dockerfile"
    depends_on:
      - "varnish"
    ports:
      - "80:80"
      - "443:443"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0


